export const INIT_DECK_SUCCESS = 'INIT_DECK_SUCCESS'
export const INIT_DECK_ERROR = 'INIT_DECK_ERROR'

export const GET_CARD_BEGIN = 'GET_CARD_BEGIN'
export const GET_CARD_SUCCESS = 'GET_CARD_SUCCESS'
export const GET_CARD_ERROR = 'GET_CARD_ERROR'
export const RESET_CARD_IN_DECK = 'RESET_CARD_IN_DECK'
